 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: personal-expense-tracker
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: personal-expense-tracker
   template:
     metadata:
       labels:
         app: personal-expense-tracker
     spec:
       containers:
       - name: personal-expense-tracker
         image: icr.io/personal-expense-tracker-prod/expense-tracker:v1
         imagePullPolicy: Always
         ports:
         - containerPort: 8080
