apiVersion: v1
kind: Service
metadata:
  name: personal-expense-tracker-service
spec:
  type: NodePort
  selector:
    app: personal-expense-tracker
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort:

